import os
import streamlit as st
from supabase import create_client

ADMIN_PASSWORD = st.secrets.get("admin_password") or os.getenv("ADMIN_PASSWORD")
SUPABASE_URL = st.secrets.get("supabase", {}).get("url") or os.getenv("SUPABASE_URL")
SUPABASE_KEY = st.secrets.get("supabase", {}).get("key") or os.getenv("SUPABASE_KEY")

if not (ADMIN_PASSWORD and SUPABASE_URL and SUPABASE_KEY):
    st.error("❌ Missing admin password or Supabase config!")
    st.stop()

# Then continue with your authentication and supabase connection...
